spring.application.name=vinyl-tracker-backend
# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.info.git.mode=full

vinyl.encryption.password=${VINYL_ENCRYPTION_PASSWORD}
vinyl.encryption.salt=${VINYL_ENCRYPTION_SALT}

jwt.secret=${JWT_SECRET:defaultSecretKeyWithSufficientLengthForHS256_32bytesMin!}
jwt.expiration=86400000 
