[package]
name = "vinyl-mcp-server"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15.7"
reqwest = { version = "0.13.5", features = ["json", "cookies", "query"] }
rmcp = { version = "3.5.0", features = ["macros", "server", "transport-io"] }
schemars = { version = "1.2.2", features = ["derive"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
