spring.application.name=vinyl-tracker-backend
# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.info.git.mode=full
# Database config will be passed via Env Vars in Docker, but defaults here for local dev if needed
